# Generated by Django 5.2 on 2025-05-10 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agencia',
            fields=[
                ('id_agencia', models.AutoField(db_column='id', default="nextval('agencia_id_agencia_seq')", primary_key=True, serialize=False)),
                ('nome', models.CharField(db_column='nome', max_length=100)),
                ('telefone', models.CharField(blank=True, db_column='telefone', max_length=11, null=True)),
                ('cep', models.CharField(db_column='endereço->cep', max_length=8)),
                ('rua', models.CharField(db_column='endereço->rua', max_length=100)),
                ('cidade', models.CharField(db_column='endereço->cidade', max_length=50)),
                ('estado', models.CharField(db_column='endereço->estado', max_length=2)),
                ('complemento', models.TextField(blank=True, db_column='endereço->complemento', null=True)),
            ],
            options={
                'db_table': 'agencia',
                'managed': False,
            },
        ),
    ]
