# Generated by Django 5.2 on 2025-05-18 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_agencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='phone',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='record',
            name='zipcode',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterModelTable(
            name='agencia',
            table='crud_locadora.agencia',
        ),
    ]
